### ISSUE TITLE
Solving Battleships

### ISSUE THREAD

**Issue by OK1FWG** [kevinychen/nikoli-puzzle-solver#5]
Hi,
by solving Battleships, after a while this error message is shown:

![image](https://github.com/kevinychen/nikoli-puzzle-solver/assets/36384850/a5e0ccb3-90f3-4b10-a04c-bdde995f55d6)

Trying to solve this puzzle:

![image](https://github.com/kevinychen/nikoli-puzzle-solver/assets/36384850/a23463eb-2009-427e-899a-1c081ff0964c)

Any clue?
W.

**Comment by kevinychen** [comment]
Thanks for pointing this out. The solver for Battleships wasn't very good, and it was timing out.

This should be fixed with #6; after that change, I successfully solved the puzzle above ([penpa URL](https://util.in:8102/penpa-edit/#m=edit&p=7VZNb+IwEL3zKyqffYjjJEBubbfdS5f9oKuqihAyNC2ogXRD2K6C+O+dGbONY7uHPVTLoQoZDW/G4xfbL5PNr62qci4S/MkBD7iAK4kSuuPBkO7gcF0v6yJPT/jptl6UFTicf7285Peq2OS9TNDoYNLbNcO0OeXN5zRjgnEWwi3YhDff013zJW1ueTOGEOMCsCudFIJ70bo3FEfvXIMiAH908MG9BXemauCzWSyfpmca/ZZmzTVnONcZVUCXrcrfOTtwwf/zcjVbItAWOEQ227vycXvIFZM9b0415bGHsmwpo6spo+ehjE+ClOfLal7k06t3oDuc7Pew9D+A8DTNkPvP1h207jjdgR2lOxbJv0+q94dFEQLSAGIEYP9egcTO6CMQGcDALjq0gDiwAYFAbAChnUFMDR4xMTWHEFNziM00JqZGjYRmCVpgYE8rAkKMaURIiFFFRA6iCxtTC13ZQEKncuhUDnVlg2CoKxurHTqcpa5s5EinstSVX0fBeRB0Km7hVAxx4SLuqguWAxdZekMS99A/ivYq9Ib6uCfAwQ2FAZ4jf6iPNLwFJTH0jpICj13sDZEQPKNgRS5pXUKy1yAg3kiyn8gGZGOyV5RzQfaG7DnZiGxCOX2U4D+J1Nyad6KTJZLe+m9d0Bs+oscdnfQyNtquZnl1MiqrlSqgQYwX6iln0I3Zpiymm211r+bQV6hZQ+sAbE0jOlBRlk/Fct3NWz6syyr3hhDM7x58+bOyurOqP6ui6AD686MD6Q7ZgeoK2p/xX1VV+dxBVqpedACjVXYq5eu6S6BWXYrqUVmzrdpn3vfYH0Y3vAUD6PUfnzr/71MHtyE4tnfpsdGhE1xWXvkD7HkDAOpV+gF3xA64I2uc0FU2oB5xA2rrGyBX4gA6KgfsDaFjVVvryMqWO07lKB6nMkWfTXov), parameters: `lengths: 111112222333445`).
